### ISSUE TITLE
Feature request: save order in which sampling units are selected

### ISSUE THREAD

**Issue by hansvancalster** [jlisic/BalancedSampling#1]
Dear Jonathan Lisic,

Thanks for this wonderful and fast implementation of the local pivotal method. In my use case, I would like to draw a spatially balanced master sample (large n, large N) and use the order in which sampling units are selected to draw a specific spatially balanced sample of size n1 << n for some subpopulation.  

Is it possible to have the function return a vector with the indices of selected sampling units in the order in which they were selected by the algorithm. This is the way the  lcube function returns its result.

All the best,
Hans Van Calster

**Comment by jlisic** [comment]
Hi Hans,

Sure, it shouldn't be too hard to do.  I'll add it to this development branch, but ultimately it would be Anton's decision if this included in the official CRAN package.  I'll work on it on the train tomorrow.

Cheers,

Jonathan

**Comment by hansvancalster** [comment]
Great! I look forward to it.

**Comment by jlisic** [comment]
If you checkout the repo, there is now an inOrder flag for lpm2_kdtree.  Let me know if you run into any issues.

**Comment by hansvancalster** [comment]
Thanks Jonathan! It works perfectly!
