### ISSUE TITLE
spatially correlated Poisson sampling

### ISSUE THREAD

**Issue by pnsinha** [jlisic/BalancedSampling#2]
Thanks for the wonderful package. Is it possible to bootstrap spatially correlated Poisson sampling?

**Comment by jlisic** [comment]
Sorry for the late response.  I'm a bit busy getting ready for JSM.  

Do you mean to bootstrap using spatially correlated Poisson sampling?  If so, then it should be more efficient than SRS for estimating a population mean etc... However, it would be less than ideal for cases where you want to capture spatial correlation between observations; perhaps a two-stage design with clustering to capture some degree of local spatial correlation may work.
